### ISSUE TITLE
Wrong A records for when using n-th depth domain names

### ISSUE THREAD

**Issue by paolomainardi** [tonistiigi/dnsdock#55]
Version: `tonistiigi/dnsdock:v1.10.0`

Docker-compose file:
```
drupal:
  build: .
  dockerfile: Dockerfile.loc
  volumes_from:
    - data
  links:
    - mariadb
    - solr
    - redis
    - blackfire
  environment:
    - DNSDOCK_ALIAS=www.sacchetti.sparkfabrik.docker.loc
  restart: always
mariadb:
  extends:
    file: docker-compose.common.yml
    service: mariadb
  volumes_from:
    - data
  environment:
    - DNSDOCK_ALIAS=mysql.www.sacchetti.sparkfabrik.docker.loc
```

DIG output:

```
~ ❯ dig @172.17.42.1 mysql.www.sacchetti.sparkfabrik.docker.loc

; <<>> DiG 9.8.3-P1 <<>> @172.17.42.1 redis.www.sacchetti.sparkfabrik.docker.loc
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17281
;; flags: qr rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;redis.www.sacchetti.sparkfabrik.docker.loc. IN A

;; ANSWER SECTION:
mysql.www.sacchetti.sparkfabrik.docker.loc. 0 IN A 172.17.42.7
mysql.www.sacchetti.sparkfabrik.docker.loc. 0 IN A 172.17.42.3
```
