### ISSUE TITLE
Please add support for external networks

### ISSUE THREAD

**Issue by loki2302** [tonistiigi/dnsdock#67]
It looks like dnsdock doesn't work when containers are attached to a custom network. Consider an example:

First. Create a custom network:
```bash
docker network create --subnet 172.25.0.0/16 test
```
Second. Make containers use this network:
```yaml
version: "2"

services:
  web1:
    image: nginx
    dns: 172.25.0.1
    environment:
      - DNSDOCK_NAME=node1
      - DNSDOCK_IMAGE=test
    networks:
      test:
        ipv4_address: 172.25.0.11

  dnsdock:
    image: tonistiigi/dnsdock
    volumes:
      - /var/run/docker.sock:/run/docker.sock
    ports:
      - 53/udp
      - 8080:80
    networks:
      test:
        ipv4_address: 172.25.0.22

  tester:
    image: ubuntu
    command: bash -c "ping node1.test.docker -c3"
    links:
      - web1
      - dnsdock
    dns: 172.25.0.22
    networks:
      test:
        ipv4_address: 172.25.0.33

networks:
  test:
    external: true
```

When I run Docker Compose, the output I see is:
```
dnsdock_1  | 2016/07/31 17:24:18 Added service: c9a99bbf7783ba5d822504829ba91e762b8c472379e5e529933c13d014b20d09 {dnsdockexperiment_dnsdock_1 dnsdock <nil> -1 []}
dnsdock_1  | 2016/07/31 17:24:18 Added service: c9a99bbf7783ba5d822504829ba91e762b8c472379e5e529933c13d014b20d09 {dnsdockexperiment_dnsdock_1 dnsdock <nil> -1 []}
dnsdock_1  | 2016/07/31 17:24:18 Added service: 08bd9894a14abf223bbdfe87ea97d108cd51fe2ab52a141024f18e3654273302 {node1 test <nil> -1 []}
dnsdock_1  | 2016/07/31 17:24:18 Added service: 8e4a4f0ea0305c426e7518a987287c1f813861366f89be4ed07626ae597ebc10 {clever_blackwell ubuntu <nil> -1 []}
dnsdock_1  | 2016/07/31 17:24:18 Added service: a7b85cbde6b0166e285c48673c41b47c181e1a9922a1d340cd5f7a38b2003c6a {dnsdockexperiment_tester_1 ubuntu <nil> -1 []}
tester_1   | ping: unknown host node1.test.docker
dnsdock_1  | 2016/07/31 17:24:18 Stopped service: a7b85cbde6b0166e285c48673c41b47c181e1a9922a1d340cd5f7a38b2003c6a
dnsdockexperiment_tester_1 exited with code 2
```

Here's what dig says:
```
dig @172.25.0.22 node1.test.docker
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @172.25.0.22 node1.test.docker
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55868
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;node1.test.docker.		IN	A

;; Query time: 1 msec
;; SERVER: 172.25.0.22#53(172.25.0.22)
;; WHEN: Sun Jul 31 13:28:15 EDT 2016
;; MSG SIZE  rcvd: 64
```

Here's what curl says:
```
curl http://172.25.0.22/services
{
	"08bd9894a14abf223bbdfe87ea97d108cd51fe2ab52a141024f18e3654273302": {
		"Name": "node1",
		"Image": "test",
		"Ip": "",
		"Ttl": -1,
		"Aliases": []
	},
	"c9a99bbf7783ba5d822504829ba91e762b8c472379e5e529933c13d014b20d09": {
		"Name": "dnsdockexperiment_dnsdock_1",
		"Image": "dnsdock",
		"Ip": "",
		"Ttl": -1,
		"Aliases": []
	}
}
```

Here's what docker inspect says:
```
docker inspect 08bd
[
    {
        "Id": "08bd9894a14abf223bbdfe87ea97d108cd51fe2ab52a141024f18e3654273302",
        ...
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "940e18a4793035e36674f4e29d5f1ec3f0fa97ed39d5d02be45a4f6f8b1bc395",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "443/tcp": null,
                "80/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/940e18a47930",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "test": {
                    "IPAMConfig": {
                        "IPv4Address": "172.25.0.11"
                    },
                    "Links": null,
                    "Aliases": [
                        "08bd9894a14a",
                        "web1"
                    ],
                    "NetworkID": "e8c5a53271330faf10d186bb73f1cc512c8153f69644a4350b12a6912dfe4cea",
                    "EndpointID": "2f9f6a82e79c401d0910526dbefd81317eab312d2ce80234043d48d434cfa19e",
                    "Gateway": "172.25.0.1",
                    "IPAddress": "172.25.0.11",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:19:00:0b"
                }
            }
        }
    }
]
```
I assume that dnsdock only looks at top level `IPAddress` and ignores the `Networks` collection. The top level `IPAddress` is OK when in bridge mode, but once you switch to external network, it's always empty.

Please consider adding support for this scenario.
